name: market-prices
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postVolume:/var/lib/postgresql

  backend:
    image: backend
    build:
      context: .
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=password;Host=db;Port=5432;Database=marketDb;
    ports:
      - 80:8080
    depends_on:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postVolume:
