name: market-prices
services:
  db:
    image: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - postVolume:/var/lib/postgresql

  backend:
    image: backend
    build:
      context: .
    restart: always
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=password;Host=db;Port=5432;Database=marketDb;
    ports:
      - 80:8080
    depends_on:
      db:
        condition: service_healthy

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postVolume:
